module.exports = {
'auto': 'automatico',
'baseline': 'linhaBase',
'bold': 'negrito',
'bolder': 'maisEscuro',
'condensed': 'condensado',
'cursive': 'cursiva',
'dashed': 'tracejada',
'dotted': 'pontilhada',
'double': 'duplo',
'expanded': 'expandida',
'extra-condensed': 'extraCondensado',
'extra-expanded':  'extraExpandida',
'fixed': 'fixo',
'inset': 'inserir',
'hidden': 'escondida',
'italic': 'inclinada',
'large':  'grande',
'smaller':'menor',
'larger' : 'maior',
'length': 'comprimento',
'light' :'leve',
'medium': 'medio',
'none': 'nenhum',
'normal' : 'normal',
'no-repeat': 'naoRepetir',
'oblique': 'obliqua',
'outset': 'inicio',
'repeat': 'repetir',
'repeat-x': 'repetirEixoX',
'repeat-y': 'repetirEixoY',
'sans-serif': 'semSerifa',
'scrool': 'rolar',
'serif': 'serifada',
'shape': 'forma',
'small': 'pequeno',
'semi-condensed': 'semiCondensado',
'semi-expanded': 'semiExpandida',
'solid': 'solida',
'solid': 'solido',
'transparent': 'transparente',
'ultra-condensed': 'ultraCondensado',
'ultra-expanded': 'ultraExpandida',
'visible': 'visivel',
'x-large' : 'extraGrande',
'xx-large': 'ultraGrande',
'x-small': 'extraPequeno',
'xx-small': 'ultraPequeno'
}
